Support of uploading artifacts to S3 buckets
mulesoft/stolon-app pull request #6
Opened 2021-04-29 19:27 UTC by UnderGreen

2021-04-29 21:56 UTC, federicoboerr commented on Jenkinsfile
> +    booleanParam(name: 'IMPORT_APP_PACKAGE',
Instead of `IMPORT_APP_PACKAGE` can we rename to `PUBLISH_APP_PACKAGE`?

2021-04-29 21:58 UTC, federicoboerr commented on Jenkinsfile
> +  String[] protectedBranches = ['master', 'support/1.12.x']
the pattern for support branches can be `support/*` as all support branches are protected.

2021-04-30 19:20 UTC, pablodcar requested changes

2021-04-30 19:20 UTC, pablodcar commented on Jenkinsfile
> +          withEnv(MAKE_ENV + ["S3_URL=${s3Url}", "artifactName=${artifactName}"]) {
just a detail, but is there a reason to send S3_URL and artifactName as env variables for sh to expand, you can use double quotes and replace in the command as you did for s3Url

2021-04-30 19:20 UTC, pablodcar commented on Jenkinsfile
> +  return false
`any` ends early if it finds an element that matches the condition, so this code can be
```
return protectedBranches.any { protectedBranch ->
  if (branchOrTagName == "${protectedBranch}") return true
  def status = sh(script: "git branch --all --contains=${branchOrTagName} | grep '[*[:space:]]*remotes/origin/${protectedBranch}\$'", returnStatus: true)
  return status == 0
}

2021-04-30 20:24 UTC, pablodcar approved these changes

2021-04-30 20:27 UTC, merged